version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto-wallet-postgres
    environment:
      POSTGRES_DB: crypto_wallet_db
      POSTGRES_USER: crypto_wallet
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crypto-wallet-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: crypto-wallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto-wallet-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: crypto-wallet-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - crypto-wallet-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: crypto-wallet-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - crypto-wallet-network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: crypto-wallet-adminer
    ports:
      - "8080:8080"
    networks:
      - crypto-wallet-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  crypto-wallet-network:
    driver: bridge
